version: "3"
services:
  hydra:
    image: ghcr.io/hydradatabase/hydra:${SOFTWARE_VERSION_TAG}
    ports:
      #- 15432:5432
      - 172.17.0.1:5234:5432
    environment:
      POSTGRES_DB: hydra
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${ADMIN_PASSWORD}
    volumes:
      - ./hydra/db:/var/lib/postgresql/data
    command: -c ssl=on -c ssl_cert_file=/etc/ssl/certs/ssl-cert-snakeoil.pem -c ssl_key_file=/etc/ssl/private/ssl-cert-snakeoil.key

  pgadmin4:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${ADMIN_PASSWORD}
      PGADMIN_LISTEN_PORT: 8080
    ports:
      - "172.17.0.1:6543:8080"
    volumes:
      - ./servers.json:/pgadmin4/servers.json
